In [65]:
import pandas as pd
import numpy as np
from pathlib import Path

In [76]:
# Load the dataset disadvantage
file_path = "/Users/pace/Desktop/Columbia Bootcamp/Final Project/poverty_all.csv"
poverty_all_df = pd.read_csv(file_path)
poverty_all_df

,dbn,school_name,cohort_year,disadv_num_total_cohort,disadv_num_grads,disadv_percent_grads,disadv_num_total_regents,disadv_percent_total_regents_cohort,disadv_num_ad_regents,disadv_percent_ad_regents_cohort,...,disadv_percent_dropout,not_disadv_num_total_cohort,not_disadv_num_grads,not_disadv_percent_grads,not_disadv_num_total_regents,not_disadv_percent_total_regents_cohort,not_disadv_num_ad_regents,not_disadv_percent_ad_regents_cohort,not_disadv_num_dropout,not_disadv_percent_dropout
0,01M292,ORCHARD COLLEGIATE ACADEMY,2003,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,01M292,ORCHARD COLLEGIATE ACADEMY,2003,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,01M292,ORCHARD COLLEGIATE ACADEMY,2003,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,01M292,ORCHARD COLLEGIATE ACADEMY,2003,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,01M292,ORCHARD COLLEGIATE ACADEMY,2003,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,4.0,44.4,3.0,33.3,0.0,0.0,3.0,33.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,21K410,ABRAHAM LINCOLN HIGH SCHOOL,2007,324.0,269.0,83.0,249.0,76.9,37.0,11.4,...,8.0,317.0,197.0,62.1,190.0,59.9,40.0,12.6,55.0,17.4
1048571,21K410,ABRAHAM LINCOLN HIGH SCHOOL,2007,326.0,283.0,86.8,283.0,86.8,59.0,18.1,...,7.1,47.0,1.0,2.1,0.0,0.0,0.0,0.0,19.0,40.4
1048572,21K410,ABRAHAM LINCOLN HIGH SCHOOL,2007,326.0,283.0,86.8,283.0,86.8,59.0,18.1,...,7.1,54.0,8.0,14.8,3.0,5.6,0.0,0.0,42.0,77.8
1048573,21K410,ABRAHAM LINCOLN HIGH SCHOOL,2007,326.0,283.0,86.8,283.0,86.8,59.0,18.1,...,7.1,73.0,58.0,79.5,58.0,79.5,12.0,16.4,8.0,11.0
1048574,21K410,ABRAHAM LINCOLN HIGH SCHOOL,2007,326.0,283.0,86.8,283.0,86.8,59.0,18.1,...,7.1,85.0,61.0,71.8,60.0,70.6,10.0,11.8,17.0,20.0

In [77]:
poverty_all_df.drop_duplicates(subset=['dbn','school_name','cohort_year'])

,dbn,school_name,cohort_year,disadv_num_total_cohort,disadv_num_grads,disadv_percent_grads,disadv_num_total_regents,disadv_percent_total_regents_cohort,disadv_num_ad_regents,disadv_percent_ad_regents_cohort,...,disadv_percent_dropout,not_disadv_num_total_cohort,not_disadv_num_grads,not_disadv_percent_grads,not_disadv_num_total_regents,not_disadv_percent_total_regents_cohort,not_disadv_num_ad_regents,not_disadv_percent_ad_regents_cohort,not_disadv_num_dropout,not_disadv_percent_dropout
0,01M292,ORCHARD COLLEGIATE ACADEMY,2003,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
180,01M292,ORCHARD COLLEGIATE ACADEMY,2004,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
360,01M292,ORCHARD COLLEGIATE ACADEMY,2005,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
540,01M292,ORCHARD COLLEGIATE ACADEMY,2006,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
720,01M292,ORCHARD COLLEGIATE ACADEMY,2007,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1047381,21K410,ABRAHAM LINCOLN HIGH SCHOOL,2003,321.0,204.0,63.6,194.0,60.4,38.0,11.8,...,8.4,47.0,1.0,2.1,0.0,0.0,0.0,0.0,19.0,40.4
1047670,21K410,ABRAHAM LINCOLN HIGH SCHOOL,2004,321.0,204.0,63.6,194.0,60.4,38.0,11.8,...,8.4,47.0,1.0,2.1,0.0,0.0,0.0,0.0,19.0,40.4
1047959,21K410,ABRAHAM LINCOLN HIGH SCHOOL,2005,321.0,204.0,63.6,194.0,60.4,38.0,11.8,...,8.4,47.0,1.0,2.1,0.0,0.0,0.0,0.0,19.0,40.4
1048248,21K410,ABRAHAM LINCOLN HIGH SCHOOL,2006,321.0,204.0,63.6,194.0,60.4,38.0,11.8,...,8.4,47.0,1.0,2.1,0.0,0.0,0.0,0.0,19.0,40.4
1048537,21K410,ABRAHAM LINCOLN HIGH SCHOOL,2007,321.0,204.0,63.6,194.0,60.4,38.0,11.8,...,8.4,47.0,1.0,2.1,0.0,0.0,0.0,0.0,19.0,40.4

In [79]:
poverty_all_df.to_csv("/Users/pace/Desktop/Columbia Bootcamp/Final Project/student_analysis_project/SQL/transformed_poverty_all", index=False)